print('=== CYBER ARCHIVES - INSCRYPTION SYSTEM ===\n')
print('Creating new storage unit...')
vault = open('new_discovery.txt', 'w')
print(f'Storage unit {vault.name} created successfully...\n')
print('Inscrybing preservation data...')
vault.write('[ENTRY 001] New quantum algorithm discovered\n')
print('Inscrybed: [ENTRY 001] New quantum algorithm discovered')
vault.write('[ENTRY 002] Efficency increased by 347%\n')
print('Inscrybed: [ENTRY 002] Efficency increased by 347%')
vault.write('[ENTRY 003] Archived by Data Archivist Trainee\n')
print('Inscrybed: [ENTRY 003] Archived by Data Archivist Trainee')
print(f'\nData inscryption complete. Sealing unit {vault.name}...')
vault.close()
print('Unit sealed Successfully. Ready for long-term preservation!')
